---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ jellyseerr_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when: jellyseerr_enabled

- name: Deploy jellyseerr config persistent volume local
  ansible.builtin.include_role:
    name: etiennebarbier.k8s_applications_utils.local_pv
  vars:
    local_pv_path: "{{ jellyseerr_config_pv_local_path }}"
    local_pv_node_affinity: "{{ jellyseerr_config_pv_local_node_affinity }}"
    local_pv_pvc_namespace: "{{ jellyseerr_namespace }}"
    local_pv_pvc_name: "jellyseerr-config"
    local_pv_size: "{{ jellyseerr_config_pv_size }}"
  when:
    - jellyseerr_enabled
    - jellyseerr_config_pv_enabled
    - jellyseerr_config_pv_creation == 'manual_local'

- name: Deploy jellyseerr config persistent volume nfs
  ansible.builtin.include_role:
    name: etiennebarbier.k8s_applications_utils.nfs_pv
  vars:
    nfs_pv_nfs_server: "{{ jellyseerr_config_pv_nfs_server }}"
    nfs_pv_nfs_path: "{{ jellyseerr_config_pv_nfs_path }}"
    nfs_pv_nfs_mount_options: "{{ jellyseerr_config_pv_nfs_mount_options }}"
    nfs_pv_pvc_namespace: "{{ jellyseerr_namespace }}"
    nfs_pv_pvc_name: "jellyseerr-config"
    nfs_pv_size: "{{ jellyseerr_config_pv_size }}"
    nfs_pv_file_owner: "{{ jellyseerr_run_user }}"
    nfs_pv_file_group: "{{ jellyseerr_run_group }}"
  when:
    - jellyseerr_enabled
    - jellyseerr_config_pv_enabled
    - jellyseerr_config_pv_creation == 'manual_nfs'

- name: Deploy jellyseerr chart with values loaded from template
  kubernetes.core.helm:
    name: jellyseerr
    release_namespace: "{{ jellyseerr_namespace }}"
    chart_ref: "{{ jellyseerr_helm_repo_name }}/jellyseerr"
    values: "{{ lookup('template', 'jellyseerr.yml.j2') | from_yaml }}"
    state: "{{ 'present' if jellyseerr_enabled else 'absent' }}"
    update_repo_cache: true
