---
- name: Create hostsgroup for FreeIPA endpoints
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: freeipa_external_hosts
  loop: "{{ freeipa_external_endpoints }}"
  changed_when: false

- name: Gather facts from each host in 'freeipa_external_hosts'
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['freeipa_external_hosts'] }}"

- name: Add ingress host to ipa-rewrite.conf
  ansible.builtin.blockinfile:
    path: /etc/httpd/conf.d/ipa-rewrite.conf
    insertbefore: '^RewriteCond %{HTTP_HOST}    !\^{{ hostvars[item].ansible_fqdn | regex_escape() }}\$ \[NC\]'
    block: |
      RewriteCond %{HTTP_HOST}    !^{{ freeipa_external_ingress_host }}$ [NC]
  delegate_to: "{{ item }}"
  loop: "{{ groups['freeipa_external_hosts'] }}"
  become: true
  register: freeipa_conf_file_modification

- name: Restart httpd service
  ansible.builtin.service:
    name: httpd
    state: restarted
  delegate_to: "{{ item }}"
  loop: "{{ groups['freeipa_external_hosts'] }}"
  become: true
  when: freeipa_conf_file_modification.changed
