---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ lidarr_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when: lidarr_enabled

- name: Deploy lidarr config persistent volume local
  ansible.builtin.include_role:
    name: etiennebarbier.k8s_applications_utils.local_pv
  vars:
    local_pv_path: "{{ lidarr_config_pv_local_path }}"
    local_pv_node_affinity: "{{ lidarr_config_pv_local_node_affinity }}"
    local_pv_pvc_namespace: "{{ lidarr_namespace }}"
    local_pv_pvc_name: "lidarr-config"
    local_pv_size: "{{ lidarr_config_pv_size }}"
  when:
    - lidarr_enabled
    - lidarr_config_pv_enabled
    - lidarr_config_pv_creation == 'manual_local'

- name: Deploy lidarr config persistent volume nfs
  ansible.builtin.include_role:
    name: etiennebarbier.k8s_applications_utils.nfs_pv
  vars:
    nfs_pv_nfs_server: "{{ lidarr_config_pv_nfs_server }}"
    nfs_pv_nfs_path: "{{ lidarr_config_pv_nfs_path }}"
    nfs_pv_nfs_mount_options: "{{ lidarr_config_pv_nfs_mount_options }}"
    nfs_pv_pvc_namespace: "{{ lidarr_namespace }}"
    nfs_pv_pvc_name: "lidarr-config"
    nfs_pv_size: "{{ lidarr_config_pv_size }}"
    nfs_pv_file_owner: "{{ lidarr_run_user }}"
    nfs_pv_file_group: "{{ lidarr_run_group }}"
  when:
    - lidarr_enabled
    - lidarr_config_pv_enabled
    - lidarr_config_pv_creation == 'manual_nfs'

- name: Deploy lidarr chart with values loaded from template
  kubernetes.core.helm:
    name: lidarr
    release_namespace: "{{ lidarr_namespace }}"
    chart_ref: "{{ lidarr_helm_repo_name }}/lidarr"
    values: "{{ lookup('template', 'lidarr.yml.j2') | from_yaml }}"
    state: "{{ 'present' if lidarr_enabled else 'absent' }}"
    update_repo_cache: true
