---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ airsonic_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when: airsonic_enabled

- name: Deploy airsonic chart with values loaded from template
  kubernetes.core.helm:
    name: airsonic
    release_namespace: "{{ airsonic_namespace }}"
    chart_ref: "{{ airsonic_helm_repo_name }}/airsonic"
    values: "{{ lookup('template', 'airsonic.yml.j2') | from_yaml }}"
    state: "{{ 'present' if airsonic_enabled | bool else 'absent' }}"
    update_repo_cache: true
